" Contact: peder.korsveien@gmail.com
" Available From: https://github.com/pederpus/dotvim
"
" The following urls are some of my inspirational sources for setting up
" this vimrc. They are worthwhile a look (use gx to open url under cursor in vim)
"
" http://github.com/lstor/vimfiles-lstor
" https://github.com/amix/vimrc
" http://www.8t8.us/vim/vim.html
" http://dougblack.io/words/a-good-vimrc.html



" gf to move to file under cursor
source $HOME/.vim/conf/plugins.vim
source $HOME/.vim/conf/plugin-settings.vim
source $HOME/.vim/conf/keyboard-mappings.vim
source $HOME/.vim/conf/system-specifics.vim

set wildignorecase
set nu
set noswapfile
colorscheme Tomorrow-Night

